name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          config_order: base.header, isocalendar, languages, stars
          base: header
          plugin_introduction: yes
          plugin_calendar: yes
          plugin_wakatime: yes
          plugin_achievements: yes
          plugin_wakatime_token: cbd713b1-31d7-4d7d-8805-b185c5e4c834
          plugin_traffic: yes
          plugin_skyline: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_activity: yes
          plugin_lines: yes
